version: "3"
services:
  nginx:
    image: nginx:1.15.1-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../home/uwork/public:/var/www/html/public:rw
      - ./u/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
      - ../logs/nginx:/var/log/nginx:rw
    networks:
      - net-php
    restart: always
    command: nginx -g 'daemon off;'
  php:
    image: registry.cn-qingdao.aliyuncs.com/php_fpm/5.6.37:v1
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ../www:/var/www/html:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ../logs/php:/usr/local/var/log:rw
    networks:
      - net-php
      - net-mysql
      - net-redis
    restart: always
    command: php-fpm


networks:
  net-php:
  net-mysql:
  net-redis:
